### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by kn1g** [spantaleev/nextcloud-docker-ansible-deploy#1]
Hey, 

I'm looking for a good private cloud solution and did a lot of research. I ended up at your project and I never did anything with ansible before. But as far as I got it this is just a script, that sets up the docker container (what I did manually) and does some config. I also want the S3 bucket as primary storage. Is the combination with goofy fast enough to run it smooth?

Do you still maintain the project and is it easy to maintain when you maybe stop maintaining it?

Best,
Nico

**Comment by spantaleev** [comment]
Hey!

I've been hosting the Nextcloud instance for me and my family with this playbook, so I intend to maintain it.
It shouldn't be too hard to fix something, if you have trouble with it.

The Goofys performance is much better than the performance it had with S3fs (used until some weeks ago).

For some reason image preview (thumbnail) generation is slow for me, but it's probably not because of slow I/O, but more importantly because of the underpowered server I run this on (only 1 CPU core).
But even with that, it does what it needs to do well enough.
