### ISSUE TITLE
FATAL: permission denied for database "nextcloud" DETAIL: User does not have CONNECT privilege.

### ISSUE THREAD

**Issue by angry-tony** [spantaleev/nextcloud-docker-ansible-deploy#2]
hello, 

after intallation, I got an error on "Initial Nextcloud configuration".
what should i do to solve it???

```
Error while trying to create admin user:
Failed to connect to the database:
An exception occured in driver: SQLSTATE[08006] [7]
FATAL: permission denied for database "nextcloud" DETAIL: User does not have CONNECT privilege.
```

**Comment by spantaleev** [comment]
This is a problem described in nextcloud/server#11311.

Looks like a workaround might be something like seen here: https://github.com/oddsund/docker-nginx-nextcloud-grav/commit/58f2ee10e5af0ad730a54bcb7ce1ad1c129e9c50

Basically, telling the Postgres container to initialize some other database (`POSTGRES_DB=whatever`) instead of a database named `nextcloud`. Doing this should leave the `nextcloud` database name available for Nextcloud to create by itself.

------------------

You might try it manually by:

- stopping all services (`systemctl stop nextcloud*`)
- modifying `/nextcloud/environment-variables/env-postgres-server-docker` so that it says something like `POSTGRES_DB=whatever`
- deleting the existing Postgres data (`rm -rf /nextcloud/postgres`)
- starting all services again (you can re-run the playbook with `--tags=start`)
- trying the Nextcloud install step again from its web interface

Re-running the playbook's installation steps (`--tags=setup-all`) in the future will overwrite the file we modified above (`/nextcloud/environment-variables/env-postgres-server-docker`), clearing our custom changes. Still, that shouldn't be a problem anymore, as Nextcloud would have created the `nextcloud` database already.

-----------------

If the above workaround works, we could fix this playbook by making it so that the `env-postgres-server-docker` file (template is in `roles/nextcloud-server/templates/env/env-postgres-server-docker.j2`) is always generated with an entry like `POSTGRES_DB=whatever`.
