### ISSUE TITLE
Reference to non-existent documentation

### ISSUE THREAD

**Issue by jahanson** [spantaleev/nextcloud-docker-ansible-deploy#60]
no documentation exists at [/docs/configuring-playbook-postgres-backup.md](https://github.com/spantaleev/nextcloud-docker-ansible-deploy/tree/master)

https://github.com/spantaleev/nextcloud-docker-ansible-deploy/blob/51b4986f7dd79cb551e514898fe66a11688eb2ca/docs/maintenance-postgres.md?plain=1#L49

**Comment by spantaleev** [comment]
Since today, this `nextcloud-docker-ansible-deploy` playbook has been merged into the [mash-playbook](https://github.com/mother-of-all-self-hosting/mash-playbook), which supports installing [Nextcloud](https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/services/nextcloud.md) and [many more](https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/supported-services.md) services.

In the new playbook, you can find the [Postgres Backup](https://github.com/mother-of-all-self-hosting/mash-playbook/blob/main/docs/services/postgres-backup.md) service and its documentation.

----

To migrate your setup from `nextcloud-docker-ansible-deploy` to `mash-playbook`, see the [migration guide](https://github.com/spantaleev/nextcloud-docker-ansible-deploy/blob/master/CHANGELOG.md#this-playbook-has-been-absorbed-into-the-mash-playbook) entry in the changelog.
